version : "2"
services:
    docker:
        container_name: jenkins-docker
        privileged: true
        image: ripperdocjenkins.azurecr.io/docker
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home

        ports:
            - 2376:2376

        networks:
            jenkins-network:
                aliases: 
                    - docker
    jenkins:
        container_name: ripperdoc-jenkins
        image: ripperdocjenkins.azurecr.io/jenkins
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
        networks:
            - jenkins-network
        ports:
            - 8080:8080
        depends_on:
            - docker
volumes:
    jenkins-data:
        driver: azure_file
        driver_opts:
            share_name: myfileshare
            storage_account_name: jenkinsdata
    jenkins-docker-certs:
        driver: azure_file
        driver_opts:
            share_name: myfileshare
            storage_account_name: jenkinsdockercerts
networks:
    jenkins-network:
        driver: bridge