version : "2"
services:
    docker:
        container_name: jenkins-docker
        privileged: true
        image: docker:dind
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
        ports: 
            - 2376:2376
        networks:
            jenkins-network:
                aliases: 
                    - docker
    jenkins:
        container_name: ripperdoc-jenkins
        build: .
        # image: jenkins/jenkinsdocker:lts-jdk11
        image: giantsweetroll/ripperdoc:jenkins
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
        networks:
            - jenkins-network
        ports:
            - 9080:8080
            - 50000:50000
        depends_on:
            - docker
volumes:
    jenkins-data:
        driver: local
    jenkins-docker-certs:
        driver: local
networks:
    jenkins-network:
        driver: bridge